python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Synthetic --test_dataset 5000 
python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Synthetic --test_dataset 10000
python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Synthetic --test_dataset 20000
python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Synthetic --test_dataset 50000
python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Synthetic --test_dataset 100000
python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Real --test_dataset com-youtube
python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Real --test_dataset amazon
python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Real --test_dataset dblp
python src/test.py --num_min 4000 --num_max 5000 --test_data_path ../DrBC_Data/Real --test_dataset com-lj
